name: Deploy to Ubuntu

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_SERVER }}
          port: ${{ secrets.SFTP_PORT }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          # will put all file under this path
          local_path: ./* # default is ./*
          # files will copy to under remote_path
          remote_path: /var/www/i4planet_openai/
          
          # sftp args
          args: '-o ConnectTimeout=5'
     
      - name: Deploy to Ubuntu server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SFTP_PORT }}
          script: |
            docker stop i4planet-openai || true
            docker rm i4planet-openai || true
            docker build -t i4planet-openai:latest /var/www/i4planet_openai/
            docker run -d -p 5000:5000 --name i4planet-openai -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} i4planet-openai:latest
