name: Deploy to Ubuntu

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t i4planet-openai:latest .

      - name: Save Docker image as tar
        run: docker save -o i4planet-openai.tar i4planet-openai:latest

      - name: Transfer Docker image to Ubuntu server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: i4planet-openai.tar
          target: /tmp/i4planet-openai.tar

      - name: Deploy to Ubuntu server
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_SERVER }}
          port: ${{ secrets.SFTP_PORT }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop i4planet-openai || true
            docker rm i4planet-openai || true
            docker load -i /tmp/i4planet-openai.tar
            docker run -d -p 5000:5000 --name i4planet-openai i4planet-openai:latest
